development:
  host: localhost
  database: communal_development

test:
  host: localhost
  database: communal_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
